export PRODUCT_NAME="mapcs"
export FREEBSD_REPO_BASE=https://github.com/HamidMapna/FreeBSD-src.git
export POUDRIERE_PORTS_GIT_URL=https://github.com/HamidMapna/FreeBSD-ports.git
export FREEBSD_BRANCH=RELENG_2_7_2
export POUDRIERE_PORTS_GIT_BRANCH=RELENG_2_7_2
unset USE_PKG_REPO_STAGING
export DEFAULT_ARCH_LIST="amd64.amd64"
export PKG_REPO_SIGNING_COMMAND="/root/sign/sign.sh ${PKG_REPO_SIGN_KEY}"
export myIPAddress=$(ifconfig | awk '/inet / && $2 != "127.0.0.1" {count++; if (count==2) print $2}')
export PKG_REPO_SERVER_DEVEL="http://${myIPAddress}/packages"
export PKG_REPO_SERVER_RELEASE="http://${myIPAddress}/packages"
export PKG_REPO_SERVER_STAGING="http://${myIPAddress}/packages"
export PKG_REPO_BRANCH_DEVEL="RELENG_2_7_2"
export PKG_REPO_BRANCH_RELEASE="RELENG_2_7_2"
export MIRROR_TYPE="none"
export POUDRIERE_PFSENSE_SRC_REPO=$(git config --get remote.upstream.url|sed 's/.*\/\(.*\)\.git/\1/g'|tr '[:upper:]' '[:lower:]')
export NO_CHECKSUM=yes
export SIGNATURE_TYPE NONE
